services:
  chatbot:
    image: thegenuinedockeruser/bauordnung-chatbot:latest
    ports:
      - "${CHAINLIT_PORT}:${CHAINLIT_PORT}"
    env_file:
      - .env
    volumes:
      - ./logfiles:/app/logfiles
