services:
  chatbot:
    image: bauordnung-chatbot:latest
    ports:
      - "${CHAINLIT_PORT}:${CHAINLIT_PORT}"
    env_file:
      - .env
    volumes:
      - ./logfiles:/app/logfiles
  watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
